import type { Metadata } from "next";
import "./globals.css";
import { ThemeProvider } from "@/components/layout/ThemeProvider";
import { Toaster } from "sonner";

export const metadata: Metadata = {
  title: "Phà AG Management App",
  description: "Generated by Tuan Pham Minh",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className="antialiased font-[Poppins] text-neutral-text-main">
        <ThemeProvider>
          {children} {/* Nội dung của (auth) hoặc (dashboard) sẽ đổ vào đây */}
        </ThemeProvider>
        <Toaster position="top-right" richColors />
      </body>
    </html>
  );
}
